.TH DOH-CLI "1" "May 2026" "doh-cli 0.8" "User Commands"

.SH NAME

doh-cli \- a simple DNS over HTTPS client.

.SH SYNOPSIS

.B doh-cli
.RI [ " OPTIONS " ]
\fIdomain\fR
[ \fIrr\fR ]

.IR rr " := { A | AAAA | CNAME | HTTPS | MX | NS | SOA | SPF | SRV | SVCB | TXT | CAA | DNSKEY | DS }"

.SH DESCRIPTION

This is a simple DoH Python client (RFC 8484, GET), which supports plain and json output.

.SH OPTIONS

.TP
\fB\-\-debug\fR
show the entire response.

.TP
\fB\-\-dns\fR \fIdns\fR
choose DoH endpoint. Possible values of \fIdns\fR are:
.RS 4
.IP "\fBlibredns\fR" 4
The default value.
.IP "\fBlibredns-ads\fR" 4
LibreDNS No-Trackers/Ads.
.IP "\fBgoogle\fR" 4
.IP "\fBcloudflare\fR" 4
.IP "\fBquad9\fR" 4
.IP "\fBcleanbrowsing\fR" 4
blocks access to adult, pornographic and explicit sites, also VPNs.
.IP "\fBcleanbrowsing-secure\fR" 4
blocks access to phishing, malware and malicious domains.
.IP "\fBcleanbrowsing-adult\fR" 4
blocks access to all adult, pornographic and explicit sites.
.IP "\fBcira\fR" 4
.IP "\fBcira-protect\fR" 4
malware and phishing protection.
.IP "\fBcira-family\fR" 4
blocking pornographic content plus protected.
.IP "\fBsecuredns\fR" 4
.IP "\fBsecuredns-ads\fR" 4
blockign ads, malware and phishing.
.RE

.TP
\fB\-\-dnssec\fR
request DNSSEC signatures.

.TP
\fB\-\-json\fR
display DNS response in json format.

.TP
\fB\-\-time\fR
show query time. This value is related to the client request towards the DoH provider, not the actual dns response.

.TP
\fB\-\-url\fR \fIurl\fP
provide your own DoH endpoint. This option overrides the \fB--dns\fR option.

.TP
\fB\-\-verbose\fR
show the entire request.

.TP
\fB\-v\fR, \fB\-\-version\fR
print version information and exit.

.SH EXAMPLES

doh-cli libredns.gr A

doh-cli --json libredns.gr A

You can use \fBjq\fR(1) to format, parse output:

doh-cli --json libredns.gr A | jq .
